server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel%20tours%20management%20system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      logging:
        log_sql_injection: true