server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel%20tours%20management%20system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG